// js/data.js

const CATEGORIES = {
  // --- CORE & API ---
  core: {
    name: "⚙️ الإضافات الأساسية",
    description: "إضافات ضرورية لعمل Vencord بشكل صحيح.",
    icon: "⚙️",
  },
  api: {
    name: "🔌 واجهات برمجة التطبيقات (API)",
    description:
      "توفر هذه الإضافات وظائف برمجية للمطورين الآخرين. **يجب تفعيلها دائمًا لضمان عمل الإضافات الأخرى بشكل صحيح.**",
    icon: "🔌",
  },
  // --- MAIN CATEGORIES ---
  appearance: {
    name: "🎨 المظهر والتخصيص",
    description: "إضافات لتغيير شكل ومظهر واجهة Discord.",
    icon: "🎨",
  },
  privacy: {
    name: "🔒 الخصوصية والأمان",
    description: "إضافات تركز على حماية خصوصيتك.",
    icon: "🔒",
  },
  fun: {
    name: "🎉 المرح والترفيه",
    description: "إضافات تضيف لمسة من المرح والتسلية.",
    icon: "🎉",
  },
  // --- SUBDIVIDED UTILITY CATEGORIES ---
  qualityOfLife: {
    name: "✨ جودة الحياة",
    description: "تحسينات صغيرة تجعل استخدام Discord أكثر سلاسة ومتعة.",
    icon: "✨",
  },
  chat: {
    name: "💬 الدردشة والرسائل",
    description: "أدوات لتحسين تجربة الكتابة، الرد، وإدارة الرسائل.",
    icon: "💬",
  },
  user: {
    name: "👤 المستخدم والملف الشخصي",
    description: "إضافات لعرض معلومات إضافية وتحسين التفاعل مع المستخدمين.",
    icon: "👤",
  },
  integrations: {
    name: "🔗 التكاملات والوسائط",
    description: "ربط Discord بخدمات أخرى وتحسين التعامل مع الوسائط.",
    icon: "🔗",
  },
  developer: {
    name: "💻 أدوات المطورين",
    description: "إضافات مفيدة لمطوري الإضافات والمستخدمين المتقدمين.",
    icon: "💻",
  },
  misc: {
    name: "🧩 متنوعة",
    description: "إضافات لا تندرج بوضوح تحت الفئات الأخرى.",
    icon: "🧩",
  },
};

const THEMES = [
  {
    name: "ClearVision",
    author: "ClearVision Team",
    description: "ثيم شفاف وقابل للتخصيص بدرجة عالية.",
    previewUrl:
      "https://gibbu.github.io/ThemePreview/?file=https://cdn.jsdelivr.net/gh/ClearVision/ClearVision-v7@d1bf5d6f79e66d834a46298db7cee1fbd362bfdc/ClearVision-v7-BetterDiscord.theme.css",
    downloadUrl: "https://betterdiscord.app/Download?id=23",
  },
  {
    name: "Dark Matter",
    author: "tropical",
    description: "تصميم داكن عصري مع تأثيرات الضوء والظل المتقدمة.",
    previewUrl:
      "https://gibbu.github.io/ThemePreview/?file=https://raw.githubusercontent.com/tropical/discord-dark-matter/master/DarkMatter.theme.css",
    downloadUrl: "https://betterdiscord.app/Download?id=45",
  },
  {
    name: "Discord+",
    author: "PlusInsta",
    description: "إعادة تصميم شامل لواجهة Discord مع تحسينات.",
    previewUrl:
      "https://gibbu.github.io/ThemePreview/?file=https://raw.githubusercontent.com/PlusInsta/discord-plus/master/DiscordPlus.theme.css",
    downloadUrl: "https://betterdiscord.app/Download?id=12",
  },
  {
    name: "NotAnotherAnimeTheme",
    author: "puckzxz",
    description: "ثيم مخصص لعشاق الأنمي مع خلفيات وألوان زاهية.",
    previewUrl:
      "https://gibbu.github.io/ThemePreview/?file=https://raw.githubusercontent.com/puckzxz/NotAnotherAnimeTheme/master/NotAnotherAnimeTheme.theme.css",
    downloadUrl: "https://betterdiscord.app/Download?id=67",
  },
  {
    name: "Midnight",
    author: "refact0r",
    description: "ثيم بسيط وأنيق بألوان داكنة مريحة للعين.",
    previewUrl:
      "https://gibbu.github.io/ThemePreview/?file=https://raw.githubusercontent.com/refact0r/midnight-discord/master/midnight.theme.css",
    downloadUrl: "https://betterdiscord.app/Download?id=89",
  },
  {
    name: "Horizontal Server List",
    author: "Gibbu",
    description: "يحول قائمة السيرفرات من العمودية إلى الأفقية.",
    previewUrl:
      "https://gibbu.github.io/ThemePreview/?file=https://raw.githubusercontent.com/DiscordStyles/HorizontalServerList/master/HorizontalServerList.theme.css",
    downloadUrl: "https://betterdiscord.app/Download?id=34",
  },
  {
    name: "Frosted Glass",
    author: "Gibbu",
    description: "تأثير الزجاج المصقول مع شفافية جميلة.",
    previewUrl:
      "https://gibbu.github.io/ThemePreview/?file=https://raw.githubusercontent.com/DiscordStyles/FrostedGlass/master/FrostedGlass.theme.css",
    downloadUrl: "https://betterdiscord.app/Download?id=56",
  },
  {
    name: "Fallout 4 Terminal",
    author: "DiscordStyles",
    description: "ثيم مستوحى من لعبة Fallout 4.",
    previewUrl:
      "https://gibbu.github.io/ThemePreview/?file=https://raw.githubusercontent.com/DiscordStyles/Fallout4Terminal/master/Fallout4Terminal.theme.css",
    downloadUrl: "https://betterdiscord.app/Download?id=78",
  },
];

const PLUGINS_DATA = [
  // --- API (Required) ---
  {
    id: "ChatInputButtonAPI",
    name: "ChatInputButtonAPI",
    author: "Vendicated",
    description: "API لإضافة أزرار إلى شريط الإدخال.",
    category: "api",
    required: true,
    settings: [],
  },
  {
    id: "CommandsAPI",
    name: "CommandsAPI",
    author: "Vendicated",
    description: "API لإنشاء أوامر مخصصة.",
    category: "api",
    required: true,
    settings: [],
  },
  {
    id: "MemberListDecoratorsAPI",
    name: "MemberListDecoratorsAPI",
    author: "Vendicated",
    description: "API لتزيين قائمة الأعضاء.",
    category: "api",
    required: true,
    settings: [],
  },
  {
    id: "MessageAccessoriesAPI",
    name: "MessageAccessoriesAPI",
    author: "Vendicated",
    description: "API لإضافة عناصر أسفل الرسائل.",
    category: "api",
    required: true,
    settings: [],
  },
  {
    id: "MessageDecorationsAPI",
    name: "MessageDecorationsAPI",
    author: "Vendicated",
    description: "API لإضافة زخارف حول الرسائل.",
    category: "api",
    required: true,
    settings: [],
  },
  {
    id: "MessageEventsAPI",
    name: "MessageEventsAPI",
    author: "Vendicated",
    description: "API للتفاعل مع أحداث الرسائل.",
    category: "api",
    required: true,
    settings: [],
  },
  {
    id: "MessagePopoverAPI",
    name: "MessagePopoverAPI",
    author: "Vendicated",
    description: "API لتخصيص قائمة الرسالة.",
    category: "api",
    required: true,
    settings: [],
  },
  {
    id: "MessageUpdaterAPI",
    name: "MessageUpdaterAPI",
    author: "Vendicated",
    description: "API لتعديل محتوى الرسائل.",
    category: "api",
    required: true,
    settings: [],
  },
  {
    id: "ServerListAPI",
    name: "ServerListAPI",
    author: "Vendicated",
    description: "API للتفاعل مع قائمة الخوادم.",
    category: "api",
    required: true,
    settings: [],
  },
  {
    id: "UserSettingsAPI",
    name: "UserSettingsAPI",
    author: "Vendicated",
    description: "API لإضافة إعدادات مخصصة للمستخدم.",
    category: "api",
    required: true,
    settings: [],
  },
  {
    id: "DynamicImageModalAPI",
    name: "DynamicImageModalAPI",
    author: "Vendicated",
    description: "API لعرض الصور في نافذة منبثقة.",
    category: "api",
    required: true,
    settings: [],
  },
  {
    id: "BadgeAPI",
    name: "BadgeAPI",
    author: "Vendicated",
    description: "API لإضافة شارات مخصصة.",
    category: "api",
    required: true,
    settings: [],
  },

  // --- Core (Required) ---
  {
    id: "CrashHandler",
    name: "CrashHandler",
    author: "Vendicated",
    description: "يعالج الأعطال غير المتوقعة.",
    category: "core",
    required: true,
    settings: [
      {
        id: "attemptToPreventCrashes",
        type: "checkbox",
        label: "محاولة منع الأعطال",
        default: true,
      },
      {
        id: "attemptToNavigateToHome",
        type: "checkbox",
        label: "الانتقال للرئيسية عند العطل",
        default: false,
      },
    ],
  },
  {
    id: "Settings",
    name: "Settings",
    author: "Vendicated",
    description: "يضيف لوحة تحكم Vencord.",
    category: "core",
    required: true,
    settings: [
      {
        id: "settingsLocation",
        type: "select",
        label: "موقع الإعدادات",
        options: [{ value: "aboveActivity", label: "فوق النشاط" }],
        default: "aboveActivity",
      },
    ],
  },
  {
    id: "SupportHelper",
    name: "SupportHelper",
    author: "Vendicated",
    description: "يوفر أدوات للمساعدة والدعم.",
    category: "core",
    required: true,
    settings: [],
  },
  {
    id: "NoTrack",
    name: "NoTrack",
    author: "Vendicated",
    description: "يمنع تتبع بيانات Discord.",
    category: "privacy",
    required: true,
    settings: [
      {
        id: "disableAnalytics",
        type: "checkbox",
        label: "تعطيل التحليلات",
        default: true,
      },
    ],
  },

  // --- Other Plugins (Alphabetical Order & Re-categorized) ---
  {
    id: "AccountPanelServerProfile",
    name: "AccountPanelServerProfile",
    author: "Vendicated",
    description: "يفتح ملفك الشخصي للخادم الحالي.",
    category: "user",
    settings: [],
  },
  {
    id: "AlwaysAnimate",
    name: "AlwaysAnimate",
    author: "Vendicated",
    description: "يجبر العناصر المتحركة على الحركة دائمًا.",
    category: "appearance",
    settings: [],
  },
  {
    id: "AlwaysExpandRoles",
    name: "AlwaysExpandRoles",
    author: "Vendicated",
    description: "يعرض قائمة الأدوار موسعة دائمًا.",
    category: "appearance",
    settings: [],
  },
  {
    id: "AlwaysTrust",
    name: "AlwaysTrust",
    author: "Vendicated",
    description: "يتجاوز تحذيرات الروابط غير الموثوقة.",
    category: "qualityOfLife",
    settings: [],
  },
  {
    id: "AnonymiseFileNames",
    name: "AnonymiseFileNames",
    author: "Vendicated",
    description: "يغير أسماء الملفات المرفوعة.",
    category: "privacy",
    settings: [],
  },
  {
    id: "AppleMusicRichPresence",
    name: "AppleMusicRichPresence",
    author: "Vendicated",
    description: "يعرض ما تستمع إليه على Apple Music.",
    category: "integrations",
    settings: [],
  },
  {
    id: "BANger",
    name: "BANger",
    author: "Vendicated",
    description: "يغير صورة GIF في نافذة تأكيد الحظر.",
    category: "fun",
    settings: [],
  },
  {
    id: "BetterFolders",
    name: "BetterFolders",
    author: "Vendicated",
    description: "يحسن عرض مجلدات الخوادم.",
    category: "appearance",
    settings: [
      {
        id: "sidebar",
        type: "checkbox",
        label: "الشريط الجانبي",
        default: true,
      },
      {
        id: "showFolderIcon",
        type: "number",
        label: "إظهار أيقونة المجلد",
        default: 1,
      },
      {
        id: "keepIcons",
        type: "checkbox",
        label: "الاحتفاظ بالأيقونات",
        default: false,
      },
      {
        id: "sidebarAnim",
        type: "checkbox",
        label: "حركة الشريط الجانبي",
        default: true,
      },
    ],
  },
  {
    id: "BetterGifAltText",
    name: "BetterGifAltText",
    author: "Vendicated",
    description: "يجعل النص البديل لصور GIF أكثر فائدة.",
    category: "appearance",
    settings: [],
  },
  {
    id: "BetterGifPicker",
    name: "BetterGifPicker",
    author: "Vendicated",
    description: "يفتح نافذة GIF على قسم 'المفضلة'.",
    category: "appearance",
    settings: [],
  },
  {
    id: "BetterNotesBox",
    name: "BetterNotesBox",
    author: "Vendicated",
    description: "يحسن صندوق الملاحظات في الملف الشخصي.",
    category: "appearance",
    settings: [],
  },
  {
    id: "BetterRoleDot",
    name: "BetterRoleDot",
    author: "Vendicated",
    description: "يحسن نقطة الدور الملونة.",
    category: "appearance",
    settings: [
      {
        id: "copyRoleColorInProfilePopout",
        type: "checkbox",
        label: "نسخ اللون في الملف الشخصي",
        default: false,
      },
    ],
  },
  {
    id: "BetterSettings",
    name: "BetterSettings",
    author: "Vendicated",
    description: "يحسن سلاسة فتح الإعدادات.",
    category: "appearance",
    settings: [],
  },
  {
    id: "BetterSessions",
    name: "BetterSessions",
    author: "Vendicated",
    description: "يحسن صفحة الجلسات بمعلومات دقيقة.",
    category: "qualityOfLife",
    settings: [
      {
        id: "backgroundCheck",
        type: "checkbox",
        label: "فحص في الخلفية",
        default: false,
      },
    ],
  },
  {
    id: "BetterUploadButton",
    name: "BetterUploadButton",
    author: "Vendicated",
    description: "يغير سلوك زر الرفع.",
    category: "chat",
    settings: [],
  },
  {
    id: "BiggerStreamPreview",
    name: "BiggerStreamPreview",
    author: "Vendicated",
    description: "يكبر نافذة معاينة البث.",
    category: "appearance",
    settings: [],
  },
  {
    id: "BlurNSFW",
    name: "BlurNSFW",
    author: "Vendicated",
    description: "يموه الصور في قنوات NSFW.",
    category: "appearance",
    settings: [],
  },
  {
    id: "CallTimer",
    name: "CallTimer",
    author: "Vendicated",
    description: "يعرض مؤقت للمكالمات.",
    category: "qualityOfLife",
    settings: [
      {
        id: "format",
        type: "select",
        label: "تنسيق الوقت",
        options: [{ value: "stopwatch", label: "ساعة إيقاف" }],
        default: "stopwatch",
      },
    ],
  },
  {
    id: "ClearURLs",
    name: "ClearURLs",
    author: "Vendicated",
    description: "يزيل معلمات التتبع من الروابط.",
    category: "privacy",
    settings: [],
  },
  {
    id: "ClientTheme",
    name: "ClientTheme",
    author: "Vendicated",
    description: "يغير لون الخلفية الرئيسي للواجهة.",
    category: "appearance",
    settings: [
      { id: "color", type: "color", label: "اللون", default: "313338" },
    ],
  },
  {
    id: "ColorSighted",
    name: "ColorSighted",
    author: "Vendicated",
    description: "يضيف تلوينًا للأزرار لتسهيل التمييز.",
    category: "appearance",
    settings: [],
  },
  {
    id: "ConsoleJanitor",
    name: "ConsoleJanitor",
    author: "Vendicated",
    description: "ينظف وحدة التحكم للمطورين.",
    category: "developer",
    settings: [],
  },
  {
    id: "ConsoleShortcuts",
    name: "ConsoleShortcuts",
    author: "Vendicated",
    description: "يضيف اختصارات لوحدة التحكم.",
    category: "developer",
    settings: [],
  },
  {
    id: "CopyEmojiMarkdown",
    name: "CopyEmojiMarkdown",
    author: "Vendicated",
    description: "نسخ الرمز التعبيري بتنسيق Markdown.",
    category: "chat",
    settings: [],
  },
  {
    id: "CopyFileContents",
    name: "CopyFileContents",
    author: "Vendicated",
    description: "نسخ المحتوى النصي للملفات.",
    category: "chat",
    settings: [],
  },
  {
    id: "CopyStickerLinks",
    name: "CopyStickerLinks",
    author: "Vendicated",
    description: "يضيف خيارًا لنسخ روابط الملصقات.",
    category: "chat",
    settings: [],
  },
  {
    id: "CopyUserURLs",
    name: "CopyUserURLs",
    author: "Vendicated",
    description: "نسخ رابط الملف الشخصي للمستخدم.",
    category: "user",
    settings: [],
  },
  {
    id: "CtrlEnterSend",
    name: "CtrlEnterSend",
    author: "Vendicated",
    description: "يغير سلوك الإرسال (Ctrl+Enter).",
    category: "chat",
    settings: [],
  },
  {
    id: "CustomIdle",
    name: "CustomIdle",
    author: "Vendicated",
    description: "تعيين حالة 'خامل' مخصصة.",
    category: "user",
    settings: [],
  },
  {
    id: "CustomRPC",
    name: "CustomRPC",
    author: "Vendicated",
    description: "إنشاء وعرض حالة نشاط مخصصة.",
    category: "user",
    settings: [],
  },
  {
    id: "Dearrow",
    name: "Dearrow",
    author: "Vendicated",
    description: "يحاول إزالة الأسهم المضللة من صور YouTube.",
    category: "integrations",
    settings: [],
  },
  {
    id: "Decor",
    name: "Decor",
    author: "Vendicated",
    description: "يتيح تخصيصات مرئية عبر CSS.",
    category: "appearance",
    settings: [],
  },
  {
    id: "DevCompanion",
    name: "DevCompanion",
    author: "Vendicated",
    description: "أدوات مساعدة لمطوري الإضافات.",
    category: "developer",
    settings: [],
  },
  {
    id: "DisableCallIdle",
    name: "DisableCallIdle",
    author: "Vendicated",
    description: "يمنع تغيير حالتك إلى 'خامل' أثناء المكالمات.",
    category: "qualityOfLife",
    settings: [],
  },
  {
    id: "DontRoundMyTimestamps",
    name: "DontRoundMyTimestamps",
    author: "Vendicated",
    description: "يعرض الطوابع الزمنية بدقة أكبر.",
    category: "chat",
    settings: [],
  },
  {
    id: "Experiments",
    name: "Experiments",
    author: "Vendicated",
    description: "يتيح الوصول إلى التجارب المخفية.",
    category: "developer",
    settings: [
      {
        id: "toolbarDevMenu",
        type: "checkbox",
        label: "قائمة المطورين",
        default: false,
      },
    ],
  },
  {
    id: "ExpressionCloner",
    name: "ExpressionCloner",
    author: "Vendicated",
    description: "نسخ الرموز التعبيرية والملصقات بين الخوادم.",
    category: "qualityOfLife",
    settings: [],
  },
  {
    id: "F8Break",
    name: "F8Break",
    author: "Vendicated",
    description: "يوقف التنفيذ عند الضغط على F8.",
    category: "developer",
    settings: [],
  },
  {
    id: "FakeNitro",
    name: "FakeNitro",
    author: "Vendicated",
    description: "يتيح استخدام بعض مزايا Nitro محليًا.",
    category: "qualityOfLife",
    settings: [
      {
        id: "enableEmojiBypass",
        type: "checkbox",
        label: "تجاوز الرموز",
        default: true,
      },
      { id: "emojiSize", type: "number", label: "حجم الرموز", default: 48 },
    ],
  },
  {
    id: "FakeProfileThemes",
    name: "FakeProfileThemes",
    author: "Vendicated",
    description: "يطبق سمات ملف شخصي مخصصة.",
    category: "appearance",
    settings: [],
  },
  {
    id: "FavoriteEmojiFirst",
    name: "FavoriteEmojiFirst",
    author: "Vendicated",
    description: "يعرض الرموز التعبيرية المفضلة أولاً.",
    category: "appearance",
    settings: [],
  },
  {
    id: "FavoriteGifSearch",
    name: "FavoriteGifSearch",
    author: "Vendicated",
    description: "حفظ مصطلحات البحث في منتقي GIF.",
    category: "chat",
    settings: [],
  },
  {
    id: "FixCodeblockGap",
    name: "FixCodeblockGap",
    author: "Vendicated",
    description: "إصلاح الفجوة في كتل الكود.",
    category: "appearance",
    settings: [],
  },
  {
    id: "FixImagesQuality",
    name: "FixImagesQuality",
    author: "Vendicated",
    description: "يحاول منع ضغط جودة الصور.",
    category: "appearance",
    settings: [],
  },
  {
    id: "FixSpotifyEmbeds",
    name: "FixSpotifyEmbeds",
    author: "Vendicated",
    description: "إصلاح تضمينات Spotify التي لا تعمل.",
    category: "integrations",
    settings: [],
  },
  {
    id: "FixYoutubeEmbeds",
    name: "FixYoutubeEmbeds",
    author: "Vendicated",
    description: "إصلاح تضمينات YouTube التي لا تعمل.",
    category: "integrations",
    settings: [],
  },
  {
    id: "ForceOwnerCrown",
    name: "ForceOwnerCrown",
    author: "Vendicated",
    description: "إجبار ظهور تاج مالك الخادم.",
    category: "appearance",
    settings: [],
  },
  {
    id: "FriendInvites",
    name: "FriendInvites",
    author: "Vendicated",
    description: "إرسال دعوات صداقة بسهولة.",
    category: "user",
    settings: [],
  },
  {
    id: "FriendsSince",
    name: "FriendsSince",
    author: "Vendicated",
    description: "يعرض تاريخ إضافة الصديق.",
    category: "user",
    settings: [],
  },
  {
    id: "FullSearchContext",
    name: "FullSearchContext",
    author: "Vendicated",
    description: "عرض سياق كامل في نتائج البحث.",
    category: "chat",
    settings: [],
  },
  {
    id: "FullUserInChatbox",
    name: "FullUserInChatbox",
    author: "Vendicated",
    description: "عرض معلومات المستخدم الكاملة في صندوق الدردشة.",
    category: "appearance",
    settings: [],
  },
  {
    id: "GameActivityToggle",
    name: "GameActivityToggle",
    author: "Vendicated",
    description: "يضيف زرًا لتبديل عرض نشاط اللعبة.",
    category: "qualityOfLife",
    settings: [
      {
        id: "oldIcon",
        type: "checkbox",
        label: "أيقونة قديمة",
        default: false,
      },
    ],
  },
  {
    id: "GifPaste",
    name: "GifPaste",
    author: "Vendicated",
    description: "لصق روابط GIF مباشرة.",
    category: "chat",
    settings: [],
  },
  {
    id: "GreetStickerPicker",
    name: "GreetStickerPicker",
    author: "Vendicated",
    description: "تحية في منتقي الملصقات.",
    category: "fun",
    settings: [],
  },
  {
    id: "HideMedia",
    name: "HideMedia",
    author: "Vendicated",
    description: "إخفاء الوسائط في القنوات المحددة.",
    category: "qualityOfLife",
    settings: [],
  },
  {
    id: "iLoveSpam",
    name: "iLoveSpam",
    author: "Vendicated",
    description: "أدوات للتعامل مع الرسائل المزعجة.",
    category: "qualityOfLife",
    settings: [],
  },
  {
    id: "IgnoreActivities",
    name: "IgnoreActivities",
    author: "Vendicated",
    description: "تجاهل أنشطة المستخدمين.",
    category: "user",
    settings: [],
  },
  {
    id: "ImageFilename",
    name: "ImageFilename",
    author: "Vendicated",
    description: "عرض اسم ملف الصورة الأصلي.",
    category: "integrations",
    settings: [],
  },
  {
    id: "ImageLink",
    name: "ImageLink",
    author: "Vendicated",
    description: "يضيف خيار 'نسخ الرابط' للصور.",
    category: "integrations",
    settings: [],
  },
  {
    id: "ImageZoom",
    name: "ImageZoom",
    author: "Vendicated",
    description: "تكبير الصور عند التمرير عليها.",
    category: "appearance",
    settings: [],
  },
  {
    id: "ImplicitRelationships",
    name: "ImplicitRelationships",
    author: "Vendicated",
    description: "إدارة العلاقات الضمنية.",
    category: "user",
    settings: [],
  },
  {
    id: "InvisibleChat",
    name: "InvisibleChat",
    author: "Vendicated",
    description: "إخفاء الدردشات.",
    category: "privacy",
    settings: [],
  },
  {
    id: "IrcColors",
    name: "IrcColors",
    author: "Vendicated",
    description: "دعم ألوان IRC في الدردشة.",
    category: "appearance",
    settings: [],
  },
  {
    id: "KeepCurrentChannel",
    name: "KeepCurrentChannel",
    author: "Vendicated",
    description: "البقاء في القناة الحالية عند الانضمام لمكالمة.",
    category: "qualityOfLife",
    settings: [],
  },
  {
    id: "LastFMRichPresence",
    name: "LastFMRichPresence",
    author: "Vendicated",
    description: "يعرض ما تستمع إليه من Last.fm.",
    category: "integrations",
    settings: [],
  },
  {
    id: "LoadingQuotes",
    name: "LoadingQuotes",
    author: "Vendicated",
    description: "عرض اقتباسات أثناء التحميل.",
    category: "fun",
    settings: [],
  },
  {
    id: "MemberCount",
    name: "MemberCount",
    author: "Vendicated",
    description: "عرض عدد أعضاء الخادم.",
    category: "qualityOfLife",
    settings: [],
  },
  {
    id: "MentionAvatars",
    name: "MentionAvatars",
    author: "Vendicated",
    description: "عرض الصور الرمزية في الإشارات.",
    category: "appearance",
    settings: [],
  },
  {
    id: "MessageClickActions",
    name: "MessageClickActions",
    author: "Vendicated",
    description: "إجراءات مخصصة عند النقر على الرسائل.",
    category: "chat",
    settings: [],
  },
  {
    id: "MessageLatency",
    name: "MessageLatency",
    author: "Vendicated",
    description: "عرض زمن وصول الرسالة.",
    category: "developer",
    settings: [],
  },
  {
    id: "MessageLogger",
    name: "MessageLogger",
    author: "Vendicated",
    description: "يسجل الرسائل المحذوفة والمعدلة.",
    category: "qualityOfLife",
    settings: [],
  },
  {
    id: "MessageTags",
    name: "MessageTags",
    author: "Vendicated",
    description: "إضافة علامات للرسائل.",
    category: "appearance",
    settings: [],
  },
  {
    id: "MessageLinkEmbeds",
    name: "MessageLinkEmbeds",
    author: "Vendicated",
    description: "يضمن تضمين محتوى الرسائل عند لصق روابطها.",
    category: "chat",
    settings: [],
  },
  {
    id: "MutualGroupDMs",
    name: "MutualGroupDMs",
    author: "Vendicated",
    description: "عرض المجموعات المشتركة.",
    category: "user",
    settings: [],
  },
  {
    id: "NewGuildSettings",
    name: "NewGuildSettings",
    author: "Vendicated",
    description: "استبدال واجهة إعدادات الخادم القديمة.",
    category: "qualityOfLife",
    settings: [],
  },
  {
    id: "NoBlockedMessages",
    name: "NoBlockedMessages",
    author: "Vendicated",
    description: "إخفاء رسالة 'Blocked Message'.",
    category: "appearance",
    settings: [],
  },
  {
    id: "NoDevtoolsWarning",
    name: "NoDevtoolsWarning",
    author: "Vendicated",
    description: "إزالة تحذير أدوات المطور.",
    category: "developer",
    settings: [],
  },
  {
    id: "NoF1",
    name: "NoF1",
    author: "Vendicated",
    description: "تعطيل فتح المساعدة بـ F1.",
    category: "qualityOfLife",
    settings: [],
  },
  {
    id: "NoMaskedUrlPaste",
    name: "NoMaskedUrlPaste",
    author: "Vendicated",
    description: "لصق الروابط كنص عادي.",
    category: "chat",
    settings: [],
  },
  {
    id: "NoMosaic",
    name: "NoMosaic",
    author: "Vendicated",
    description: "يمنع عرض الصور بشكل فسيفساء.",
    category: "appearance",
    settings: [
      {
        id: "noMosaicAttachments",
        type: "checkbox",
        label: "المرفقات",
        default: true,
      },
      {
        id: "noMosaicEmbeds",
        type: "checkbox",
        label: "التضمينات",
        default: true,
      },
    ],
  },
  {
    id: "NoOnboardingDelay",
    name: "NoOnboardingDelay",
    author: "Vendicated",
    description: "إزالة تأخير الانضمام للخوادم.",
    category: "qualityOfLife",
    settings: [],
  },
  {
    id: "NoPendingCount",
    name: "NoPendingCount",
    author: "Vendicated",
    description: "إخفاء عدد طلبات الصداقة المعلقة.",
    category: "appearance",
    settings: [],
  },
  {
    id: "NoProfileThemes",
    name: "NoProfileThemes",
    author: "Vendicated",
    description: "تعطيل سمات الملفات الشخصية.",
    category: "appearance",
    settings: [],
  },
  {
    id: "NoReplyMention",
    name: "NoReplyMention",
    author: "Vendicated",
    description: "إزالة الإشارة (ping) عند الرد.",
    category: "chat",
    settings: [],
  },
  {
    id: "NoServerEmojis",
    name: "NoServerEmojis",
    author: "Vendicated",
    description: "تعطيل الرموز التعبيرية للخادم.",
    category: "chat",
    settings: [],
  },
  {
    id: "NoSystemBadge",
    name: "NoSystemBadge",
    author: "Vendicated",
    description: "إخفاء شارة النظام.",
    category: "appearance",
    settings: [],
  },
  {
    id: "NoTypingAnimation",
    name: "NoTypingAnimation",
    author: "Vendicated",
    description: "إزالة مؤشر الكتابة.",
    category: "appearance",
    settings: [],
  },
  {
    id: "NoUnblockToJump",
    name: "NoUnblockToJump",
    author: "Vendicated",
    description: "الانتقال لرسالة محظورة بدون فك الحظر.",
    category: "qualityOfLife",
    settings: [],
  },
  {
    id: "NormalizeMessageLinks",
    name: "NormalizeMessageLinks",
    author: "Vendicated",
    description: "توحيد شكل روابط الرسائل.",
    category: "chat",
    settings: [],
  },
  {
    id: "NotificationVolume",
    name: "NotificationVolume",
    author: "Vendicated",
    description: "التحكم في مستوى صوت الإشعارات.",
    category: "qualityOfLife",
    settings: [],
  },
  {
    id: "OnePingPerDM",
    name: "OnePingPerDM",
    author: "Vendicated",
    description: "إشارة واحدة لكل محادثة خاصة.",
    category: "chat",
    settings: [],
  },
  {
    id: "oneko",
    name: "oneko",
    author: "Vendicated",
    description: "قطة تتبع مؤشر الفأرة.",
    category: "fun",
    settings: [],
  },
  {
    id: "OpenInApp",
    name: "OpenInApp",
    author: "Vendicated",
    description: "فتح الروابط في تطبيقاتها الأصلية.",
    category: "integrations",
    settings: [],
  },
  {
    id: "OverrideForumDefaults",
    name: "OverrideForumDefaults",
    author: "Vendicated",
    description: "تجاوز الإعدادات الافتراضية للمنتديات.",
    category: "qualityOfLife",
    settings: [],
  },
  {
    id: "PauseInvitesForever",
    name: "PauseInvitesForever",
    author: "Vendicated",
    description: "إيقاف دعوات الخادم بشكل دائم.",
    category: "privacy",
    settings: [],
  },
  {
    id: "PermissionFreeWill",
    name: "PermissionFreeWill",
    author: "Vendicated",
    description: "تجاوز قيود الصلاحيات.",
    category: "developer",
    settings: [],
  },
  {
    id: "PermissionsViewer",
    name: "PermissionsViewer",
    author: "Vendicated",
    description: "عرض صلاحيات المستخدمين.",
    category: "qualityOfLife",
    settings: [],
  },
  {
    id: "petpet",
    name: "petpet",
    author: "Vendicated",
    description: "إنشاء صور GIF 'petpet'.",
    category: "fun",
    settings: [],
  },
  {
    id: "PictureInPicture",
    name: "PictureInPicture",
    author: "Vendicated",
    description: "تفعيل وضع 'صورة داخل صورة' للبث.",
    category: "integrations",
    settings: [],
  },
  {
    id: "PinDMs",
    name: "PinDMs",
    author: "Vendicated",
    description: "يسمح بتثبيت المحادثات الخاصة.",
    category: "qualityOfLife",
    settings: [
      {
        id: "canCollapseDmSection",
        type: "checkbox",
        label: "طي القسم",
        default: false,
      },
    ],
  },
  {
    id: "PlainFolderIcon",
    name: "PlainFolderIcon",
    author: "Vendicated",
    description: "استخدام أيقونة مجلد بسيطة.",
    category: "appearance",
    settings: [],
  },
  {
    id: "PlatformIndicators",
    name: "PlatformIndicators",
    author: "Vendicated",
    description: "إظهار مؤشرات المنصة (سطح مكتب/هاتف).",
    category: "appearance",
    settings: [],
  },
  {
    id: "PreviewMessage",
    name: "PreviewMessage",
    author: "Vendicated",
    description: "عرض معاينة للرسالة التي ترد عليها.",
    category: "chat",
    settings: [],
  },
  {
    id: "QuickMention",
    name: "QuickMention",
    author: "Vendicated",
    description: "إشارة سريعة للمستخدمين.",
    category: "chat",
    settings: [],
  },
  {
    id: "QuickReply",
    name: "QuickReply",
    author: "Vendicated",
    description: "الرد السريع على الرسائل.",
    category: "chat",
    settings: [],
  },
  {
    id: "ReadAllNotificationsButton",
    name: "ReadAllNotificationsButton",
    author: "Vendicated",
    description: "زر لقراءة كل الإشعارات.",
    category: "qualityOfLife",
    settings: [],
  },
  {
    id: "ReactErrorDecoder",
    name: "ReactErrorDecoder",
    author: "Vendicated",
    description: "فك تشفير أخطاء React.",
    category: "developer",
    settings: [],
  },
  {
    id: "RelationshipNotifier",
    name: "RelationshipNotifier",
    author: "Vendicated",
    description: "إشعارات عند تغييرات الصداقة.",
    category: "user",
    settings: [],
  },
  {
    id: "ReplaceGoogleSearch",
    name: "ReplaceGoogleSearch",
    author: "Vendicated",
    description: "استبدال بحث Google.",
    category: "integrations",
    settings: [],
  },
  {
    id: "ReplyTimestamp",
    name: "ReplyTimestamp",
    author: "Vendicated",
    description: "إظهار الطابع الزمني في الردود.",
    category: "appearance",
    settings: [],
  },
  {
    id: "RevealAllSpoilers",
    name: "RevealAllSpoilers",
    author: "Vendicated",
    description: "كشف كل المحتوى المحروق (Spoilers).",
    category: "qualityOfLife",
    settings: [],
  },
  {
    id: "ReverseImageSearch",
    name: "ReverseImageSearch",
    author: "Vendicated",
    description: "البحث العكسي عن الصور.",
    category: "integrations",
    settings: [],
  },
  {
    id: "ReviewDB",
    name: "ReviewDB",
    author: "Vendicated",
    description: "قاعدة بيانات لمراجعات المستخدمين.",
    category: "user",
    settings: [],
  },
  {
    id: "RoleColorEverywhere",
    name: "RoleColorEverywhere",
    author: "Vendicated",
    description: "إظهار لون الدور في كل مكان.",
    category: "appearance",
    settings: [],
  },
  {
    id: "SecretRingToneEnabler",
    name: "SecretRingToneEnabler",
    author: "Vendicated",
    description: "تفعيل نغمة الرنين السرية.",
    category: "fun",
    settings: [],
  },
  {
    id: "SendTimestamps",
    name: "SendTimestamps",
    author: "Vendicated",
    description: "إرسال طوابع زمنية ديناميكية.",
    category: "chat",
    settings: [],
  },
  {
    id: "ServerInfo",
    name: "ServerInfo",
    author: "Vendicated",
    description: "عرض معلومات الخادم.",
    category: "qualityOfLife",
    settings: [],
  },
  {
    id: "ServerListIndicators",
    name: "ServerListIndicators",
    author: "Vendicated",
    description: "مؤشرات في قائمة الخوادم.",
    category: "appearance",
    settings: [],
  },
  {
    id: "ShikiCodeblocks",
    name: "ShikiCodeblocks",
    author: "Vendicated",
    description: "تلوين الكود باستخدام Shiki.",
    category: "appearance",
    settings: [],
  },
  {
    id: "ShowAllMessageButtons",
    name: "ShowAllMessageButtons",
    author: "Vendicated",
    description: "إظهار كل أزرار الرسائل دائمًا.",
    category: "appearance",
    settings: [],
  },
  {
    id: "ShowConnections",
    name: "ShowConnections",
    author: "Vendicated",
    description: "عرض اتصالات المستخدم في أماكن أكثر.",
    category: "user",
    settings: [],
  },
  {
    id: "ShowHiddenChannels",
    name: "ShowHiddenChannels",
    author: "Vendicated",
    description: "إظهار القنوات المخفية.",
    category: "qualityOfLife",
    settings: [],
  },
  {
    id: "ShowHiddenThings",
    name: "ShowHiddenThings",
    author: "Vendicated",
    description: "إظهار الأشياء المخفية.",
    category: "developer",
    settings: [],
  },
  {
    id: "ShowMeYourName",
    name: "ShowMeYourName",
    author: "Vendicated",
    description: "إظهار اسمك كما يراه الآخرون.",
    category: "user",
    settings: [],
  },
  {
    id: "ShowTimeoutDuration",
    name: "ShowTimeoutDuration",
    author: "Vendicated",
    description: "إظهار مدة الإسكات (Timeout).",
    category: "qualityOfLife",
    settings: [],
  },
  {
    id: "SilentMessageToggle",
    name: "SilentMessageToggle",
    author: "Vendicated",
    description: "زر لإرسال رسائل صامتة.",
    category: "chat",
    settings: [],
  },
  {
    id: "SilentTyping",
    name: "SilentTyping",
    author: "Vendicated",
    description: "الكتابة بدون إظهار مؤشر الكتابة للآخرين.",
    category: "privacy",
    settings: [],
  },
  {
    id: "SortFriendRequests",
    name: "SortFriendRequests",
    author: "Vendicated",
    description: "ترتيب طلبات الصداقة.",
    category: "user",
    settings: [],
  },
  {
    id: "SpotifyControls",
    name: "SpotifyControls",
    author: "Vendicated",
    description: "عناصر تحكم Spotify.",
    category: "integrations",
    settings: [],
  },
  {
    id: "SpotifyCrack",
    name: "SpotifyCrack",
    author: "Vendicated",
    description: "تفعيل ميزات Spotify Premium داخل Discord.",
    category: "integrations",
    settings: [],
  },
  {
    id: "SpotifyShareCommands",
    name: "SpotifyShareCommands",
    author: "Vendicated",
    description: "أوامر لمشاركة Spotify.",
    category: "integrations",
    settings: [],
  },
  {
    id: "StartupTimings",
    name: "StartupTimings",
    author: "Vendicated",
    description: "عرض توقيتات بدء التشغيل.",
    category: "developer",
    settings: [],
  },
  {
    id: "StickerPaste",
    name: "StickerPaste",
    author: "Vendicated",
    description: "لصق الملصقات كروابط.",
    category: "chat",
    settings: [],
  },
  {
    id: "StreamerModeOnStream",
    name: "StreamerModeOnStream",
    author: "Vendicated",
    description: "تفعيل وضع البث تلقائيًا.",
    category: "qualityOfLife",
    settings: [],
  },
  {
    id: "Summaries",
    name: "Summaries",
    author: "Vendicated",
    description: "تلخيص محادثات الذكاء الاصطناعي.",
    category: "chat",
    settings: [],
  },
  {
    id: "SuperReactionTweaks",
    name: "SuperReactionTweaks",
    author: "Vendicated",
    description: "تعديلات على التفاعلات الفائقة.",
    category: "chat",
    settings: [],
  },
  {
    id: "TextReplace",
    name: "TextReplace",
    author: "Vendicated",
    description: "استبدال النصوص.",
    category: "chat",
    settings: [],
  },
  {
    id: "ThemeAttributes",
    name: "ThemeAttributes",
    author: "Vendicated",
    description: "سمات إضافية للثيمات.",
    category: "appearance",
    settings: [],
  },
  {
    id: "Translate",
    name: "Translate",
    author: "Vendicated",
    description: "ترجمة الرسائل.",
    category: "chat",
    settings: [],
  },
  {
    id: "TypingIndicator",
    name: "TypingIndicator",
    author: "Vendicated",
    description: "مؤشر كتابة مخصص.",
    category: "appearance",
    settings: [],
  },
  {
    id: "TypingTweaks",
    name: "TypingTweaks",
    author: "Vendicated",
    description: "تعديلات على مؤشر الكتابة.",
    category: "appearance",
    settings: [],
  },
  {
    id: "Unindent",
    name: "Unindent",
    author: "Vendicated",
    description: "إزالة المسافات البادئة.",
    category: "chat",
    settings: [],
  },
  {
    id: "UnlockedAvatarZoom",
    name: "UnlockedAvatarZoom",
    author: "Vendicated",
    description: "تكبير غير محدود للصور الرمزية.",
    category: "user",
    settings: [],
  },
  {
    id: "UnsuppressEmbeds",
    name: "UnsuppressEmbeds",
    author: "Vendicated",
    description: "إلغاء قمع التضمينات.",
    category: "chat",
    settings: [],
  },
  {
    id: "UserMessagesPronouns",
    name: "UserMessagesPronouns",
    author: "Vendicated",
    description: "إظهار ضمائر المستخدمين في الرسائل.",
    category: "appearance",
    settings: [],
  },
  {
    id: "UserVoiceShow",
    name: "UserVoiceShow",
    author: "Vendicated",
    description: "يعرض المستخدمين في القنوات الصوتية.",
    category: "user",
    settings: [
      {
        id: "showInUserProfileModal",
        type: "checkbox",
        label: "إظهار في الملف الشخصي",
        default: true,
      },
    ],
  },
  {
    id: "USRBG",
    name: "USRBG",
    author: "Vendicated",
    description: "خلفيات مخصصة لملفات تعريف المستخدمين.",
    category: "appearance",
    settings: [],
  },
  {
    id: "ValidReply",
    name: "ValidReply",
    author: "Vendicated",
    description: "إصلاح مشكلة عدم تحميل الردود.",
    category: "qualityOfLife",
    settings: [],
  },
  {
    id: "ValidUser",
    name: "ValidUser",
    author: "Vendicated",
    description: "استرداد معلومات المستخدم بواسطة ID.",
    category: "user",
    settings: [],
  },
  {
    id: "VcNarrator",
    name: "VcNarrator",
    author: "Vendicated",
    description: "راوي للمحادثات الصوتية.",
    category: "qualityOfLife",
    settings: [],
  },
  {
    id: "VencordToolbox",
    name: "VencordToolbox",
    author: "Vendicated",
    description: "صندوق أدوات Vencord.",
    category: "developer",
    settings: [],
  },
  {
    id: "ViewIcons",
    name: "ViewIcons",
    author: "Vendicated",
    description: "عرض الصور الرمزية والبانرات بحجمها الكامل.",
    category: "user",
    settings: [],
  },
  {
    id: "ViewRaw",
    name: "ViewRaw",
    author: "Vendicated",
    description: "عرض المصدر الخام للرسائل.",
    category: "developer",
    settings: [],
  },
  {
    id: "VoiceChatDoubleClick",
    name: "VoiceChatDoubleClick",
    author: "Vendicated",
    description: "النقر المزدوج في المحادثات الصوتية.",
    category: "qualityOfLife",
    settings: [],
  },
  {
    id: "VoiceDownload",
    name: "VoiceDownload",
    author: "Vendicated",
    description: "تنزيل الرسائل الصوتية.",
    category: "chat",
    settings: [],
  },
  {
    id: "VoiceMessages",
    name: "VoiceMessages",
    author: "Vendicated",
    description: "تمكين الرسائل الصوتية.",
    category: "chat",
    settings: [],
  },
  {
    id: "VolumeBooster",
    name: "VolumeBooster",
    author: "Vendicated",
    description: "زيادة مستوى الصوت فوق 200%.",
    category: "qualityOfLife",
    settings: [],
  },
  {
    id: "WhoReacted",
    name: "WhoReacted",
    author: "Vendicated",
    description: "إظهار من تفاعل على الرسائل.",
    category: "chat",
    settings: [],
  },
  {
    id: "XSOverlay",
    name: "XSOverlay",
    author: "Vendicated",
    description: "تكامل مع XSOverlay.",
    category: "integrations",
    settings: [],
  },
  {
    id: "YoutubeAdblock",
    name: "YoutubeAdblock",
    author: "Vendicated",
    description: "مانع إعلانات يوتيوب.",
    category: "integrations",
    settings: [],
  },
  {
    id: "YoutubeAdblock.desktop",
    name: "YoutubeAdblock.desktop",
    author: "Vendicated",
    description: "مانع إعلانات يوتيوب لسطح المكتب.",
    category: "integrations",
    settings: [],
  },
];

const SUGGESTED_PLUGINS = [
  "SpotifyCrack",
  "ShowHiddenChannels",
  "FakeNitro",
  "ImageZoom",
  "Dearrow",
  "FixYoutubeEmbeds",
  "YoutubeAdblock",
  "ClearURLs",
  "BetterFolders",
  "BetterRoleDot",
  "AlwaysAnimate",
  "FavoriteEmojiFirst",
  "FixImagesQuality",
  "NoTypingAnimation",
  "BetterUploadButton",
  "BetterSessions",
  "CallTimer",
  "CopyUserURLs",
  "ExpressionCloner",
  "FriendsSince",
  "GameActivityToggle",
  "MessageLinkEmbeds",
  "PinDMs",
  "PreviewMessage",
  "ReadAllNotificationsButton",
  "ReverseImageSearch",
  "SendTimestamps",
  "ServerInfo",
  "ShowConnections",
  "Translate",
  "UserVoiceShow",
  "ValidReply",
  "ValidUser",
  "ViewIcons",
  "VolumeBooster",
];

// Attach all data to the window object
window.VenShortData = {
  CATEGORIES,
  THEMES,
  PLUGINS_DATA,
  SUGGESTED_PLUGINS,
};
